filamentcolors/api/urls.py
from django.urls import include, path, re_path
from rest_framework import routers

from filamentcolors.api.views import (
    FilamentTypeViewSet,
    ManufacturerViewSet,
    PantoneColorViewSet,
    RALColorViewSet,
    SwatchViewSet,
    db_version,
)

router = routers.DefaultRouter()

router.register(r"filament_type", FilamentTypeViewSet, basename="filament_type")
router.register(r"swatch", SwatchViewSet, basename="swatch")
router.register(r"manufacturer", ManufacturerViewSet, basename="manufacturer")
router.register(r"pantone", PantoneColorViewSet, basename="pantone")
router.register(r"ral", RALColorViewSet, basename="ral")

urlpatterns = [
    re_path(r"^api/", include(router.urls)),
    path("api/version/", db_version, name="db_version"),
]

filamentcolors/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.contrib.sitemaps import GenericSitemap
from django.contrib.sitemaps.views import sitemap
from django.urls import include, path

from filamentcolors import altcha_views, staff_views, views
from filamentcolors.api.urls import urlpatterns as api_urls
from filamentcolors.models import Swatch
from filamentcolors.sitemaps import StaticViewSitemap

handler400 = "filamentcolors.views.error_400"
handler404 = "filamentcolors.views.error_404"
handler500 = "filamentcolors.views.error_500"

sitemaps = {
    "static": StaticViewSitemap,
    "swatches": GenericSitemap(
        {
            "queryset": Swatch.objects.filter(published=True).order_by("id"),
            "date_field": "date_published",
        }
    ),
}
urlpatterns = [
    # Primary site URLs
    path("", views.homepage, name="homepage"),
    path("library/sort/<str:method>/", views.librarysort, name="librarysort"),
    path(
        "library/collection/edit/<str:ids>/",
        views.edit_swatch_collection,
        name="edit_collection",
    ),
    path(
        "library/collection/<str:ids>/",
        views.swatch_collection,
        name="swatchcollection",
    ),
    path("library/", views.librarysort, name="library"),
    path(
        "swatch/<str:swatch_id>/opengraph/", views.opengraph_card, name="opengraph_card"
    ),
    path("swatch/<str:swatch_id>/", views.swatch_detail, name="swatchdetail"),
    path(
        "library/manufacturer/<str:mfr_id>/",
        views.manufacturersort,
        name="manufacturersort",
    ),
    path("library/manufacturer/", views.manufacturer_list, name="mfr_list"),
    path("library/filament_type/<str:f_type_id>/", views.typesort, name="typesort"),
    path(
        "library/color_family/<str:family_id>/",
        views.colorfamilysort,
        name="color_family_sort",
    ),
    path("donating/", views.donation_page, name="donations"),
    path("monetary_donating/", views.monetary_donation_page, name="monetary_donations"),
    path("work_with_us/", views.work_with_us, name="work_with_us"),
    path("inventory/", views.inventory_page, name="inventory"),
    path("inventory_search/", views.inventory_search, name="inventory_search"),
    path("about/", views.about_page, name="about"),
    path("the_librarians/", views.about_me, name="about_us"),
    path("colormatch/", views.colormatch, name="colormatch"),
    path(
        "welcome_experience_images/<int:image_id>/",
        views.get_welcome_experience_image,
        name="welcome_experience_image",
    ),
    path(
        "welcome_experience_video",
        views.get_welcome_experience_video,
        name="welcome_experience_video",
    ),
    path(
        "reportbadlink/<int:swatch_id>/<str:link_type>/",
        views.report_bad_link,
        name="report_bad_link",
    ),
    path("visualizer/", views.swatch_field_visualizer, name="visualizer"),
    path("", include("plausible_proxy.urls")),
    path(
        "altcha/get_challenge/", altcha_views.get_challenge, name="altcha_get_challenge"
    ),
    path(
        "altcha/verify_challenge/",
        altcha_views.verify_challenge,
        name="altcha_verify_challenge",
    ),
    # Admin urls
    path("admin/", admin.site.urls),
    path("logout/", staff_views.logout_view, name="logout"),
    path("add/swatch/", staff_views.add_swatch_landing, name="add_swatch_landing"),
    path(
        "add/swatch/inventory/<int:swatch_id>",
        staff_views.add_swatch,
        name="add_swatch_from_inventory",
    ),
    path("add/swatch/new/", staff_views.add_swatch, name="add_swatch"),
    path("add/manufacturer/", staff_views.add_manufacturer, name="add_mfr"),
    path("add/filamenttype/", staff_views.add_filament_type, name="add_filament_type"),
    path("add/inventory/", staff_views.add_inventory_swatch, name="add_inventory"),
    path("add/retailer/", staff_views.add_retailer, name="add_retailer"),
    path(
        "recalculate_color/<int:swatch_id>/",
        staff_views.recalculate_color,
        name="recalculate_color",
    ),
    path(
        "force_swatch_color/<int:swatch_id>/",
        staff_views.force_swatch_color,
        name="force_swatch_color",
    ),
    path(
        "set_colors/",
        staff_views.set_colors_for_unpublished_swatches,
        name="set_colors",
    ),
    path(
        "update_lab_colors/",
        staff_views.set_colors_for_published_rgb_swatches,
        name="update_lab_colors",
    ),
    path(
        "update_images/<int:swatch_id>/",
        staff_views.update_swatch_images,
        name="update_images",
    ),
    path(
        "edit/<int:swatch_id>/purchase_locations/",
        staff_views.view_purchase_locations,
        name="view_purchase_locations",
    ),
    path(
        "edit/<int:swatch_id>/purchase_location/<int:location_id>",
        staff_views.edit_purchase_location,
        name="edit_purchase_location",
    ),
    path(
        "add/<int:swatch_id>/purchase_location/",
        staff_views.add_purchase_location,
        name="add_purchase_location",
    ),
    path(
        "edit/<int:swatch_id>/",
        staff_views.swatch_edit,
        name="edit_swatch",
    ),
    path(
        "sitemap.xml",
        sitemap,
        {"sitemaps": sitemaps},
        name="django.contrib.sitemaps.views.sitemap",
    ),
    # Event / Special URLs
    # ...
    # Old links that need to exist for a while and just redirect.
    # Remove each of them after a reasonable amount of time has passed -- probably a few months.
]


if settings.DEBUG:
    urlpatterns += [
        path("__debug__/", include("debug_toolbar.urls")),
        path(
            "testpage/",
            views.testpage,
            name="testpage",
        ),
    ]
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

urlpatterns += api_urls

filamentcolors/forms.py
from django import forms
from django.core.validators import MaxValueValidator, MinValueValidator
from django.db.models.functions import Lower
from django.forms import ClearableFileInput, TextInput

from filamentcolors.constants import LAB
from filamentcolors.models import FilamentType, Manufacturer, Retailer, Swatch


class CustomClearableFileInputField(ClearableFileInput):
    template_name = "widgets/clearable_file_input.html"


class SwatchForm(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["lab_l"].required = True
        self.fields["lab_a"].required = True
        self.fields["lab_b"].required = True
        self.fields["image_front"].required = True
        self.fields["image_back"].required = True
        self.fields["manufacturer"].widget.attrs.update({"autofocus": "autofocus"})

    manufacturer = forms.ModelChoiceField(
        queryset=Manufacturer.objects.all().order_by(Lower("name"))
    )
    filament_type = forms.ModelChoiceField(
        queryset=FilamentType.objects.all().order_by(Lower("name"))
    )

    class Meta:
        model = Swatch
        fields = [
            "filament_type",
            "color_name",
            "lab_l",
            "lab_a",
            "lab_b",
            "td",
            "color_parent",
            "alt_color_parent",
            "manufacturer",
            "amazon_purchase_link",
            "mfr_purchase_link",
            "image_front",
            "image_back",
            "image_other",
            "notes",
            "donated_by",
        ]
        widgets = {
            "image_front": CustomClearableFileInputField,
            "image_back": CustomClearableFileInputField,
            "image_other": CustomClearableFileInputField,
            "td": TextInput(),
        }


class SwatchFormNoImages(forms.ModelForm):
    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["lab_l"].required = True
        self.fields["lab_a"].required = True
        self.fields["lab_b"].required = True
        self.fields["color_name"].required = True
        self.fields["manufacturer"].required = True
        self.fields["filament_type"].required = True
        self.fields["color_parent"].required = True

    manufacturer = forms.ModelChoiceField(
        queryset=Manufacturer.objects.all().order_by(Lower("name"))
    )
    filament_type = forms.ModelChoiceField(
        queryset=FilamentType.objects.all().order_by(Lower("name"))
    )
    td = forms.FloatField(required=False)

    class Meta:
        model = Swatch
        fields = [
            "manufacturer",
            "color_name",
            "lab_l",
            "lab_a",
            "lab_b",
            "computed_lab",
            "td",
            "filament_type",
            "color_parent",
            "alt_color_parent",
            "amazon_purchase_link",
            "mfr_purchase_link",
            "notes",
            "donated_by",
        ]


class SwatchUpdateImagesForm(forms.ModelForm):
    class Meta:
        model = Swatch
        fields = [
            "image_front",
            "image_back",
            "image_other",
        ]
        widgets = {
            "image_front": CustomClearableFileInputField,
            "image_back": CustomClearableFileInputField,
            "image_other": CustomClearableFileInputField,
        }


class ListSwatchInventoryForm(forms.Form):
    _qs = (
        Swatch.objects.select_related("manufacturer")
        .prefetch_related("filament_type")
        .filter(published=False)
        .order_by(Lower("manufacturer__name"), Lower("color_name"))
    )
    colormatched_swatches = forms.ModelChoiceField(
        _qs.exclude(hex_color__exact=""), required=False
    )
    unpublished_swatches = forms.ModelChoiceField(_qs.filter(), required=False)


class ManufacturerForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["name"].widget.attrs.update({"autofocus": "autofocus"})

    class Meta:
        model = Manufacturer
        fields = ["name", "website"]


class RetailerForm(forms.ModelForm):
    class Meta:
        model = Retailer
        fields = "__all__"


class PurchaseLocationForm(forms.Form):
    retailer = forms.ModelChoiceField(queryset=Retailer.objects.all())
    url = forms.URLField()


class FilamentTypeForm(forms.ModelForm):

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["name"].widget.attrs.update({"autofocus": "autofocus"})

    class Meta:
        model = FilamentType
        fields = ["name", "hot_end_temp", "bed_temp", "parent_type"]


class InventoryForm(forms.ModelForm):
    manufacturer = forms.ModelChoiceField(
        queryset=Manufacturer.objects.all().order_by(Lower("name"))
    )
    filament_type = forms.ModelChoiceField(
        queryset=FilamentType.objects.all().order_by(Lower("name"))
    )

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields["filament_type"].widget.attrs.update(
            {"autofocus": "autofocus", "required": "required"}
        )

    class Meta:
        model = Swatch
        fields = [
            "filament_type",
            "color_name",
            "color_parent",
            "alt_color_parent",
            "manufacturer",
            "donated_by",
        ]


class ManualLabValueForm(forms.Form):
    lab_l = forms.FloatField(
        min_value=LAB["L"]["min"],
        max_value=LAB["L"]["max"],
        validators=[
            MinValueValidator(LAB["L"]["min"]),
            MaxValueValidator(LAB["L"]["max"]),
        ],
    )
    lab_a = forms.FloatField(
        min_value=LAB["A"]["min"],
        max_value=LAB["A"]["max"],
        validators=[
            MinValueValidator(LAB["A"]["min"]),
            MaxValueValidator(LAB["A"]["max"]),
        ],
    )
    lab_b = forms.FloatField(
        min_value=LAB["B"]["min"],
        max_value=LAB["B"]["max"],
        validators=[
            MinValueValidator(LAB["B"]["min"]),
            MaxValueValidator(LAB["B"]["max"]),
        ],
    )

filamentcolors/templates/base.html
{% load static %}

<!DOCTYPE html>
<html lang="en">
<head>
  {% include 'partials/head.partial' %}
  {% block title %}
    <title>{{ title|default:"FilamentColors" }}</title>
  {% endblock title %}
  {% block meta_description %}
    <meta
      name="twitter:description"
      content="FilamentColors.xyz: find the best colors for your 3D printing projects!"
    >
    <meta
      name="description"
      content="FilamentColors.xyz: find the best colors for your 3D printing projects!"
    >
  {% endblock %}

  {% block meta_title %}
    <meta name="twitter:title" content="FilamentColors.xyz">
    <meta property="og:title" content="FilamentColors.xyz">
  {% endblock %}

  {% block meta_img %}
    <meta name="twitter:image:src" content="https://filamentcolors.xyz{% static 'generic_opengraph.png' %}">
    <meta property="og:image" content="https://filamentcolors.xyz{% static 'generic_opengraph.png' %}">
  {% endblock %}
</head>

<body
  hx-ext="morph" {# Allow using the morph transition. #}
  hx-target="#main"
  hx-boost="true"  {# Make all <a> tags htmx-compatible. #}
  hx-swap="show:window:top"  {# Always swap the full element and the target & show the navbar. #}
  hx-push-url="true" {# Update the URL that displays in the browser. #}
  hx-indicator="#loading" {# The location of the loading spinner. #}
>

{% include 'components/indicators/loading_screen.partial' %}

{% if navbar_message %}
  {% include 'components/alerts/navbar_message.partial' %}
{% endif %}
{% include 'partials/navbar.partial' %}

{% if launch_welcome_modal %}
  {% include 'modals/welcome_modal.partial' %}
{% endif %}

<noscript>
  {% include 'components/alerts/no-js-alert.partial' %}
</noscript>

<main
  id="main"
  hx-swap="innerHTML scroll:window:top show:window:top"
  hx-history-elt
>
  {% block content %}
  {% endblock content %}
</main>

{% include 'partials/browser_console_message.partial' %}

{% include 'partials/footer.partial' %}
</body>
</html>

filamentcolors/templates/generic_form.html
{% extends base_template %}
{% load static widget_tweaks %}

{% block content %}
  <div class="container mt-4">
    {% include 'partials/messages.partial' %}
    <h1>{{ header }}</h1>
    <h4>{{ subheader }}</h4>

    <div class="row">
      <div class="col"></div>
      <div class="col-md-8 col-lg-8 col-xl-8">
        {% if "/add/" in request.path %}
          <div
            class="alert alert-warning"
            id="mfrAffAlert"
            style="display: none"
            role="alert"
          >
            <strong><span id="mfrAffName"></span></strong> has an affiliate portal!
            Link: <a
              href="#"
              id="mfrAffAlertLink"
              target="_blank"
              class="alert-link"
          ></a>
          </div>
          <div id="similar-swatch-alert" style="display: none">
            <div class="alert alert-danger" role="alert">
              Found similar swatches...
              <div id="similar-swatch-content"></div>
            </div>
          </div>
          <script type="text/javascript">
            function resetAlertContent() {
              $("#similar-swatch-content").empty();
            }

            function enableSubmitLoadingButton() {
              $("#submitButton").addClass("d-none");
              $("#submitButtonLoading").removeClass("d-none");
            }

            function disableSubmitLoadingButton() {
              $("#submitButton").removeClass("d-none");
              $("#submitButtonLoading").addClass("d-none");
            }

            function checkForDuplicates() {
              const name_obj = $("#id_color_name");
              const mfr_obj = $("#id_manufacturer option:selected");
              const alert_obj = $("#similar-swatch-alert");

              // Check to see if we have the data we need to check. If we don't,
              // just hide the element. Doesn't matter if it has data in it or not
              // because we'll wipe it before we write to it or display it again.
              if (mfr_obj.text() === "---------" || name_obj.val() === "") {
                alert_obj.css("display", "none");
                return;
              }
              let mfr_id = mfr_obj.val();
              const URL = `/api/swatch/?color_name__icontains=${name_obj.val()}&manufacturer__id=${mfr_id}&published=None`;
              enableSubmitLoadingButton();
              $.getJSON(URL, function(data) {
                let items = [];
                let unpublished_str = "";
                if (data.results.length === 0) {
                  alert_obj.css("display", "none");
                  resetAlertContent();
                  disableSubmitLoadingButton();
                  return;
                }
                $.each(data.results, function(key, value) {
                  unpublished_str = value.published ? "" : " (unpublished)";
                  items.push(`<li>${value.manufacturer.name} - ${value.color_name} ${value.filament_type.name}${unpublished_str}</li>`);
                });
                resetAlertContent();
                const alert_content = $("#similar-swatch-content");
                const new_list = $("<ul/>", {
                  "class": "mb-0",
                  html: items.join("")
                });
                alert_content.append(new_list);
                alert_obj.css("display", "block");
                disableSubmitLoadingButton();
              });
            }
            {% if 'add/inventory' in request.path or 'add/swatch/new' in request.path %}
              $(document).ready(function() {
                $("#id_color_name").change(checkForDuplicates);
                $("#id_manufacturer").change(checkForDuplicates);
              });
            {% endif %}
          </script>
        {% endif %}

        {% if header_js_buttons or header_link_buttons %}
          <div class="row">
            {% for item in header_js_buttons %}
              <div class="col-md-6 col-xl mt-2 d-grid">
                <button class="btn btn-primary"
                        onclick="{{ item.onclick }}">{{ item.text }}</button>
              </div>
            {% endfor %}
            {% for item in header_link_buttons %}
              <div class="col-md-6 col-xl mt-2 d-grid">
                <a href="{% url item.reverse_url %}"
                   class="btn btn-primary">{{ item.text }}</a>
              </div>
            {% endfor %}
          </div>
        {% endif %}

        <div class="container mt-3">
          {% if swatch %}
            <div class="text-center">
              <img style="width: 600px" src="{{ swatch.image_front.url }}"
                   alt="The front of the swatch in question.">
            </div>
          {% endif %}
          {# Lifted from https://simpleisbetterthancomplex.com/article/2017/08/19/how-to-render-django-form-manually.html #}
          {% if form.is_multipart %}
            {# properly handle the file uploads #}
            <form novalidate enctype="multipart/form-data" method="post" action="">
          {% else %}
            <form novalidate method="post" action="">
          {% endif %}
          <div class="errorMessages"></div>
          {% csrf_token %}
          {% for hidden_field in form.hidden_fields %}
            {{ hidden_field }}
          {% endfor %}

          {% if form.non_field_errors %}
            <div class="alert alert-danger" role="alert">
              {% for error in form.non_field_errors %}
                {{ error }}
              {% endfor %}
            </div>
          {% endif %}
          {% for field in form.visible_fields %}
            <div class="mt-3">
              {% if form.is_bound %}
                {% if field.errors %}
                  {{ field|add_label_class:"form-label" }}
                  {{ field|add_class:"form-control is-invalid" }}
                  {% for error in field.errors %}
                    <div class="invalid-feedback">
                      {{ error }}
                    </div>
                  {% endfor %}
                {% else %}
                  {{ field|add_label_class:"form-label" }}
                  {{ field|add_class:"form-control is-valid" }}
                {% endif %}
              {% else %}
                {% if field.field.widget.input_type == 'file' %}
                  <div class="my-auto pe-3 text-body-secondary">{{ field.label }}:</div>
                  {{ field|add_class:"form-control"|attr:"type=file"|add_class:"file-input" }}
                {% elif field.field.widget.input_type == 'select' %}
                  <div>
                    <label for="{{ field.auto_id }}">
                      {{ field.label }}
                    </label>
                    {{ field|add_class:"form-control" }}
                  </div>
                {% else %}
                  {{ field|add_label_class:"form-label" }}
                  {{ field|add_class:"form-control" }}
                {% endif %}
              {% endif %}

              {% if field.help_text %}
                <small class="form-text text-body-secondary">{{ field.help_text }}</small>
              {% endif %}
            </div>
          {% endfor %}
          <button type="submit" id="submitButton" class="btn btn-primary mt-4">Submit</button>
          <button id="submitButtonLoading" class="btn btn-primary mt-4 d-none" type="button" disabled>
            <span class="spinner-border spinner-border-sm" aria-hidden="true"></span>
            <span class="visually-hidden" role="status">Loading...</span>
          </button>

          </form>
        </div>
      </div>
      <div class="col"></div>
    </div>
  </div>

  <script>
    $(document).ready(function() {
      // set up new inputs
      var inputs = document.querySelectorAll(".inputfile");
      Array.prototype.forEach.call(inputs, function(input) {
        var label = input.previousElementSibling;

        input.addEventListener("change", function(e) {
          var fileName = "";

          fileName = e.target.value.split("\\").pop();

          if (fileName)
            label.innerText = fileName;
          else
            label.innerText = "browse";
        });
      });

      // from https://www.tjvantoll.com/2012/08/05/html5-form-validation-showing-all-error-messages/
      var createAllErrors = function() {
        var form = $(this);
        var errorList = $(".errorMessages");

        var showAllErrorMessages = function() {
          errorList.innerHTML = "";

          // Find all invalid fields within the form.
          var invalidFields = form.find(":invalid").each(function(index, node) {

            // Find the field's corresponding label
            var label = $("label[for=" + node.id + "] "),
              // Opera incorrectly does not fill the validationMessage property.
              message = node.validationMessage || "Invalid value.";

            // jquery won't add the same class multiple times, so we can have
            // addClass run for each loop.
            errorList.addClass("mt-3");
            errorList.append(
              "<div class=\"alert alert-danger\" role=\"alert\">\n" + label.html() + " " + message + "\n</div>"
            );
          });
        };

        // Support Safari
        form.on("submit", function(event) {
          if (this.checkValidity && !this.checkValidity()) {
            $(this).find(":invalid").first().focus();
            event.preventDefault();
          }
        });

        $("input[type=submit], button:not([type=button])", form)
          .on("click", showAllErrorMessages);

        $("input", form).on("keypress", function(event) {
          var type = $(this).attr("type");
          if (/date|email|month|number|search|tel|text|time|url|week/.test(type)
            && event.keyCode === 13) {
            showAllErrorMessages();
          }
        });
      };

      $("form").each(createAllErrors);
    });
  </script>

  {# Put application-specific imports down here. #}
  {% include "partials/swatch_add_js.partial" %}

{% endblock content %}

filamentcolors/templates/partial_base.html
{% block content %}
{% endblock content %}

{% if title %}
  <div class="d-none" id="newTitle">{{ title }}</div>
{% endif %}